from pathlib import Path
import io, math, requests, pandas as pd, numpy as np

CORE=Path("research_output/btc_eth_regime_stage8_year_anatomy")
OUT=Path("research_output/core_ema_allocation")
EMA_URL="https://raw.githubusercontent.com/duuu-hub/bb-scanner/research-btc-strategy-lab-replication/research/btc_strategy_lab_replication/out/funding_trades.csv"

def perf(r):
    r=np.asarray(r,float); r=r[np.isfinite(r)]
    curve=np.cumprod(1+r); full=np.r_[1.,curve]
    dd=full/np.maximum.accumulate(full)-1
    yrs=len(r)/365.25
    return dict(total_return_pct=(full[-1]-1)*100,
      cagr_pct=((full[-1]**(1/yrs)-1)*100 if yrs>0 and full[-1]>0 else np.nan),
      mdd_pct=dd.min()*100,
      sharpe=(np.mean(r)/np.std(r)*math.sqrt(365.25) if np.std(r)>0 else np.nan))

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    # Core daily strategy returns generated by Stage8 logic are not persisted; rebuild from yearly anatomy is impossible.
    # Download Binance daily BTC/ETH via the Stage8 module and reuse its exact panel() logic.
    import sys; sys.path.insert(0,"research")
    import btc_eth_regime_stage8_year_anatomy as c
    data={s:c.load(s) for s in c.SYMS}; x=c.panel(data)
    x=x[["datetime_utc","BTCUSDT_open","BTCUSDT_close","ETHUSDT_open","ETHUSDT_close","position","strategy_ret"]].copy()
    x["date"]=x.datetime_utc.dt.normalize()

    ema=pd.read_csv(io.StringIO(requests.get(EMA_URL,timeout=30).text))
    ema["entry_time"]=pd.to_datetime(ema.entry_time,utc=True); ema["exit_time"]=pd.to_datetime(ema.exit_time,utc=True)
    # EMA daily mark-to-market using BTC daily open->close, exact overlap horizon.
    x["ema_position"]=0.0
    for _,t in ema.iterrows():
        x.loc[(x.datetime_utc>=t.entry_time.normalize())&(x.datetime_utc<=t.exit_time.normalize()),"ema_position"]=1.0
    btc_intr=x.BTCUSDT_close/x.BTCUSDT_open-1
    # same 0.1%/side EMA cost, charged on daily position transitions
    eturn=x.ema_position.diff().abs().fillna(x.ema_position.abs())
    x["ema_ret"]=x.ema_position*btc_intr-eturn*0.001
    x["core_ret"]=x.strategy_ret/100.0

    start=max(ema.entry_time.min().normalize(),x.datetime_utc.min()); end=min(ema.exit_time.max().normalize(),x.datetime_utc.max())
    z=x[(x.datetime_utc>=start)&(x.datetime_utc<=end)].copy()
    z["overlap"]=(z.position==1)&(z.ema_position==1)

    rows=[]
    for w in np.arange(0,1.0001,.05): # w = EMA weight
        rr=w*z.ema_ret+(1-w)*z.core_ret
        p=perf(rr)
        years=[]
        for yr,g in z.assign(rr=rr).groupby(z.datetime_utc.dt.year):
            years.append(perf(g.rr.values)["total_return_pct"])
        rows.append({"ema_weight":round(float(w),2),"core_weight":round(float(1-w),2),**p,
          "positive_years":sum(v>0 for v in years),"worst_year_pct":min(years)})
    pd.DataFrame(rows).to_csv(OUT/"allocation_grid.csv",index=False)

    # overlap-only: contiguous overlap days compounded, for descriptive comparison.
    o=z[z.overlap].copy()
    variants={"EMA":o.ema_ret,"CORE":o.core_ret,"FIFTY_FIFTY":.5*o.ema_ret+.5*o.core_ret}
    pd.DataFrame([{"variant":k,**perf(v.values)} for k,v in variants.items()]).to_csv(OUT/"overlap_only_3way.csv",index=False)
    print(pd.read_csv(OUT/"allocation_grid.csv").to_string(index=False))
    print("\nOVERLAP ONLY\n",pd.read_csv(OUT/"overlap_only_3way.csv").to_string(index=False))

if __name__=="__main__": main()

# trigger allocation run
