import pandas as pd,glob
fs=glob.glob("raw/**/raw.csv",recursive=True)
print("FILES",fs)
if not fs: raise RuntimeError("no raw.csv found")
d=pd.concat([pd.read_csv(f) for f in fs],ignore_index=True)
r=pd.read_csv("reg/btc_regime.csv")
d["date"]=d["date"].astype(str)
d=d.merge(r[["date","btc_regime"]],on="date",how="left")
d["year"]=pd.to_numeric(d["year"])
print("REGIME_COUNTS")
print(d.groupby(["year","btc_regime"]).size().to_string())
d.to_csv("bear_raw_events.csv",index=False)
